/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "auth.login": [],
    "auth.logout": [],
    "books.file": [
        {
            "name": "book",
            "required": true,
            "binding": "id"
        }
    ],
    "books.advanced-search": [],
    "books.index": [],
    "books.store": [],
    "books.show": [
        {
            "name": "book",
            "required": true,
            "binding": "id"
        }
    ],
    "books.update": [
        {
            "name": "book",
            "required": true,
            "binding": "id"
        }
    ],
    "books.destroy": [
        {
            "name": "book",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
